name: Update Docker Hub Description
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Modify readme for DockerHub
        run: |
          sed -i 's/# Docker Hub Description/# [Docker Hub Description](https:\/\/github.com\/peter-evans\/dockerhub-description)/' README.md
          sed -i 's/(LICENSE)/(https:\/\/github.com\/peter-evans\/dockerhub-description\/blob\/master\/LICENSE)/' README.md

      - name: Docker Hub Description
        uses: ./
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }
          repository: sudobox/sudobox-mount
          short-description: Alpine Based rclone mount with mergerfs included 
          readme-filepath: README.md 
