   name: ci

on:
  push:
    branches: main

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      -
        name: Build and push arm64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./linux-arm64.Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            sudobox/sudobox-mount:arm64-alpine
            ghcr.io/sudobox-io/docker-mount:arm64-alpine
      -
        name: Build and push amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./linux-amd64.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            sudobox/sudobox-mount:amd64-alpine
            ghcr.io/sudobox-io/docker-mount:amd64-alpine
      -
        name: Build and push arm32v7
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./linux-arm-v7.Dockerfile
          platforms: linux/armhf
          push: true
          tags: |
            ssudobox/sudobox-mount:arm32v7-alpine
            ghcr.io/sudobox-io/docker-mount:arm32v7-alpine 
